id: AEBFAD030
title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual for
  The Vajrakīla Root Tantra Section'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.752853
  last_modified_at: 2022-03-01 06:30:26.752856
