id: AEBFAD030
title: The Eight-Branch Offering from the Gyüluk Phurba
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.755489
  last_modified_at: 2022-03-01 06:30:26.755494
