id: AEBFAD030
title: The Wisdom Mind Practice of One Kīla
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.762384
  last_modified_at: 2022-03-01 06:30:26.762387
