id: AEBFAD030
title: 'Vajrakīla Prayer: A Rain of Accomplishments'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.764067
  last_modified_at: 2022-03-01 06:30:26.764069
