id: AEBFAD030
title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.757935
  last_modified_at: 2022-03-01 06:30:26.757938
