id: AEBFAD030
title: Vajrakīla Tsok Prayer from Sangtik Korsum
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.765853
  last_modified_at: 2022-03-01 06:30:26.765855
