id: AEBFAD030
title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.746895
  last_modified_at: 2022-03-01 06:30:26.746898
