id: AEBFAD030
title: A Vajrakīla Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.742418
  last_modified_at: 2022-03-01 06:30:26.742421
