id: AEBFAD030
title: 'Offering Clouds of Samantabhadra: Confession and Fulfilment'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.750610
  last_modified_at: 2022-03-01 06:30:26.750613
