id: AEBFAD030
title: Invocation of the VidyÄdhara Gurus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:30:26.749314
  last_modified_at: 2022-03-01 06:30:26.749317
